[package]
name = "kmer"
version = "0.1.0"
authors = ["bhillmann <hillmannben@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.18"
bio = "0.32.0"